/*
 * Copyright (c) 2025. Ingo Noka
 * This file belongs to project qrdata.
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
 * Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
 *
 */

package com.ingonoka.qrdata.transcode

/**
 * Country code according to ISO standards.
 *
 * @property name The name of the country
 * @property twoLetter The two-letter code for the country.
 * @property threeLetter The three-letter code for the country.
 * @property numerical The numerical code for the country.
 */
data class CountryCode(
    val name: String,
    val twoLetter: String,
    val threeLetter: String,
    val numerical: Int
)

/**
 * List of all country codes known to the application.
 */
@Suppress("SpellCheckingInspection")
val countryCodes = mapOf(
    4 to CountryCode("Afghanistan", "AF", "AFG", 4),
    8 to CountryCode("Albania", "AL", "ALB", 8),
    12 to CountryCode("Algeria", "DZ", "DZA", 12),
    16 to CountryCode("American Samoa", "AS", "ASM", 16),
    20 to CountryCode("Andorra", "AD", "AND", 20),
    24 to CountryCode("Angola", "AO", "AGO", 24),
    660 to CountryCode("Anguilla", "AI", "AIA", 660),
    10 to CountryCode("Antarctica", "AQ", "ATA", 10),
    28 to CountryCode("Antigua and Barbuda", "AG", "ATG", 28),
    32 to CountryCode("Argentina", "AR", "ARG", 32),
    51 to CountryCode("Armenia", "AM", "ARM", 51),
    533 to CountryCode("Aruba", "AW", "ABW", 533),
    36 to CountryCode("Australia", "AU", "AUS", 36),
    40 to CountryCode("Austria", "AT", "AUT", 40),
    31 to CountryCode("Azerbaijan", "AZ", "AZE", 31),
    44 to CountryCode("Bahamas (the)", "BS", "BHS", 44),
    48 to CountryCode("Bahrain", "BH", "BHR", 48),
    50 to CountryCode("Bangladesh", "BD", "BGD", 50),
    52 to CountryCode("Barbados", "BB", "BRB", 52),
    112 to CountryCode("Belarus", "BY", "BLR", 112),
    56 to CountryCode("Belgium", "BE", "BEL", 56),
    84 to CountryCode("Belize", "BZ", "BLZ", 84),
    204 to CountryCode("Benin", "BJ", "BEN", 204),
    60 to CountryCode("Bermuda", "BM", "BMU", 60),
    64 to CountryCode("Bhutan", "BT", "BTN", 64),
    68 to CountryCode("Bolivia (Plurinational State of)", "BO", "BOL", 68),
    535 to CountryCode("Bonaire, Sint Eustatius and Saba", "BQ", "BES", 535),
    70 to CountryCode("Bosnia and Herzegovina", "BA", "BIH", 70),
    72 to CountryCode("Botswana", "BW", "BWA", 72),
    74 to CountryCode("Bouvet Island", "BV", "BVT", 74),
    76 to CountryCode("Brazil", "BR", "BRA", 76),
    86 to CountryCode("British Indian Ocean Territory (the)", "IO", "IOT", 86),
    96 to CountryCode("Brunei Darussalam", "BN", "BRN", 96),
    100 to CountryCode("Bulgaria", "BG", "BGR", 100),
    854 to CountryCode("Burkina Faso", "BF", "BFA", 854),
    108 to CountryCode("Burundi", "BI", "BDI", 108),
    132 to CountryCode("Cabo Verde", "CV", "CPV", 132),
    116 to CountryCode("Cambodia", "KH", "KHM", 116),
    120 to CountryCode("Cameroon", "CM", "CMR", 120),
    124 to CountryCode("Canada", "CA", "CAN", 124),
    136 to CountryCode("Cayman Islands (the)", "KY", "CYM", 136),
    140 to CountryCode("Central African Republic (the)", "CF", "CAF", 140),
    148 to CountryCode("Chad", "TD", "TCD", 148),
    152 to CountryCode("Chile", "CL", "CHL", 152),
    156 to CountryCode("China", "CN", "CHN", 156),
    162 to CountryCode("Christmas Island", "CX", "CXR", 162),
    166 to CountryCode("Cocos (Keeling) Islands (the)", "CC", "CCK", 166),
    170 to CountryCode("Colombia", "CO", "COL", 170),
    174 to CountryCode("Comoros (the)", "KM", "COM", 174),
    180 to CountryCode("Congo (the Democratic Republic of the)", "CD", "COD", 180),
    178 to CountryCode("Congo (the)", "CG", "COG", 178),
    184 to CountryCode("Cook Islands (the)", "CK", "COK", 184),
    188 to CountryCode("Costa Rica", "CR", "CRI", 188),
    191 to CountryCode("Croatia", "HR", "HRV", 191),
    192 to CountryCode("Cuba", "CU", "CUB", 192),
    531 to CountryCode("Curaçao", "CW", "CUW", 531),
    196 to CountryCode("Cyprus", "CY", "CYP", 196),
    203 to CountryCode("Czechia", "CZ", "CZE", 203),
    384 to CountryCode("Côte d'Ivoire", "CI", "CIV", 384),
    208 to CountryCode("Denmark", "DK", "DNK", 208),
    262 to CountryCode("Djibouti", "DJ", "DJI", 262),
    212 to CountryCode("Dominica", "DM", "DMA", 212),
    214 to CountryCode("Dominican Republic (the)", "DO", "DOM", 214),
    218 to CountryCode("Ecuador", "EC", "ECU", 218),
    818 to CountryCode("Egypt", "EG", "EGY", 818),
    222 to CountryCode("El Salvador", "SV", "SLV", 222),
    226 to CountryCode("Equatorial Guinea", "GQ", "GNQ", 226),
    232 to CountryCode("Eritrea", "ER", "ERI", 232),
    233 to CountryCode("Estonia", "EE", "EST", 233),
    748 to CountryCode("Eswatini", "SZ", "SWZ", 748),
    231 to CountryCode("Ethiopia", "ET", "ETH", 231),
    238 to CountryCode("Falkland Islands (the) [Malvinas]", "FK", "FLK", 238),
    234 to CountryCode("Faroe Islands (the)", "FO", "FRO", 234),
    242 to CountryCode("Fiji", "FJ", "FJI", 242),
    246 to CountryCode("Finland", "FI", "FIN", 246),
    250 to CountryCode("France", "FR", "FRA", 250),
    254 to CountryCode("French Guiana", "GF", "GUF", 254),
    258 to CountryCode("French Polynesia", "PF", "PYF", 258),
    260 to CountryCode("French Southern Territories (the)", "TF", "ATF", 260),
    266 to CountryCode("Gabon", "GA", "GAB", 266),
    270 to CountryCode("Gambia (the)", "GM", "GMB", 270),
    268 to CountryCode("Georgia", "GE", "GEO", 268),
    276 to CountryCode("Germany", "DE", "DEU", 276),
    288 to CountryCode("Ghana", "GH", "GHA", 288),
    292 to CountryCode("Gibraltar", "GI", "GIB", 292),
    300 to CountryCode("Greece", "GR", "GRC", 300),
    304 to CountryCode("Greenland", "GL", "GRL", 304),
    308 to CountryCode("Grenada", "GD", "GRD", 308),
    312 to CountryCode("Guadeloupe", "GP", "GLP", 312),
    316 to CountryCode("Guam", "GU", "GUM", 316),
    320 to CountryCode("Guatemala", "GT", "GTM", 320),
    831 to CountryCode("Guernsey", "GG", "GGY", 831),
    324 to CountryCode("Guinea", "GN", "GIN", 324),
    624 to CountryCode("Guinea-Bissau", "GW", "GNB", 624),
    328 to CountryCode("Guyana", "GY", "GUY", 328),
    332 to CountryCode("Haiti", "HT", "HTI", 332),
    334 to CountryCode("Heard Island and McDonald Islands", "HM", "HMD", 334),
    336 to CountryCode("Holy See (the)", "VA", "VAT", 336),
    340 to CountryCode("Honduras", "HN", "HND", 340),
    344 to CountryCode("Hong Kong", "HK", "HKG", 344),
    348 to CountryCode("Hungary", "HU", "HUN", 348),
    352 to CountryCode("Iceland", "IS", "ISL", 352),
    356 to CountryCode("India", "IN", "IND", 356),
    360 to CountryCode("Indonesia", "ID", "IDN", 360),
    364 to CountryCode("Iran (Islamic Republic of)", "IR", "IRN", 364),
    368 to CountryCode("Iraq", "IQ", "IRQ", 368),
    372 to CountryCode("Ireland", "IE", "IRL", 372),
    833 to CountryCode("Isle of Man", "IM", "IMN", 833),
    376 to CountryCode("Israel", "IL", "ISR", 376),
    380 to CountryCode("Italy", "IT", "ITA", 380),
    388 to CountryCode("Jamaica", "JM", "JAM", 388),
    392 to CountryCode("Japan", "JP", "JPN", 392),
    832 to CountryCode("Jersey", "JE", "JEY", 832),
    400 to CountryCode("Jordan", "JO", "JOR", 400),
    398 to CountryCode("Kazakhstan", "KZ", "KAZ", 398),
    404 to CountryCode("Kenya", "KE", "KEN", 404),
    296 to CountryCode("Kiribati", "KI", "KIR", 296),
    408 to CountryCode("Korea (the Democratic People's Republic of)", "KP", "PRK", 408),
    410 to CountryCode("Korea (the Republic of)", "KR", "KOR", 410),
    414 to CountryCode("Kuwait", "KW", "KWT", 414),
    417 to CountryCode("Kyrgyzstan", "KG", "KGZ", 417),
    418 to CountryCode("Lao People's Democratic Republic (the)", "LA", "LAO", 418),
    428 to CountryCode("Latvia", "LV", "LVA", 428),
    422 to CountryCode("Lebanon", "LB", "LBN", 422),
    426 to CountryCode("Lesotho", "LS", "LSO", 426),
    430 to CountryCode("Liberia", "LR", "LBR", 430),
    434 to CountryCode("Libya", "LY", "LBY", 434),
    438 to CountryCode("Liechtenstein", "LI", "LIE", 438),
    440 to CountryCode("Lithuania", "LT", "LTU", 440),
    442 to CountryCode("Luxembourg", "LU", "LUX", 442),
    446 to CountryCode("Macao", "MO", "MAC", 446),
    450 to CountryCode("Madagascar", "MG", "MDG", 450),
    454 to CountryCode("Malawi", "MW", "MWI", 454),
    458 to CountryCode("Malaysia", "MY", "MYS", 458),
    462 to CountryCode("Maldives", "MV", "MDV", 462),
    466 to CountryCode("Mali", "ML", "MLI", 466),
    470 to CountryCode("Malta", "MT", "MLT", 470),
    584 to CountryCode("Marshall Islands (the)", "MH", "MHL", 584),
    474 to CountryCode("Martinique", "MQ", "MTQ", 474),
    478 to CountryCode("Mauritania", "MR", "MRT", 478),
    480 to CountryCode("Mauritius", "MU", "MUS", 480),
    175 to CountryCode("Mayotte", "YT", "MYT", 175),
    484 to CountryCode("Mexico", "MX", "MEX", 484),
    583 to CountryCode("Micronesia (Federated States of)", "FM", "FSM", 583),
    498 to CountryCode("Moldova (the Republic of)", "MD", "MDA", 498),
    492 to CountryCode("Monaco", "MC", "MCO", 492),
    496 to CountryCode("Mongolia", "MN", "MNG", 496),
    499 to CountryCode("Montenegro", "ME", "MNE", 499),
    500 to CountryCode("Montserrat", "MS", "MSR", 500),
    504 to CountryCode("Morocco", "MA", "MAR", 504),
    508 to CountryCode("Mozambique", "MZ", "MOZ", 508),
    104 to CountryCode("Myanmar", "MM", "MMR", 104),
    516 to CountryCode("Namibia", "NA", "NAM", 516),
    520 to CountryCode("Nauru", "NR", "NRU", 520),
    524 to CountryCode("Nepal", "NP", "NPL", 524),
    528 to CountryCode("Netherlands (the)", "NL", "NLD", 528),
    540 to CountryCode("New Caledonia", "NC", "NCL", 540),
    554 to CountryCode("New Zealand", "NZ", "NZL", 554),
    558 to CountryCode("Nicaragua", "NI", "NIC", 558),
    562 to CountryCode("Niger (the)", "NE", "NER", 562),
    566 to CountryCode("Nigeria", "NG", "NGA", 566),
    570 to CountryCode("Niue", "NU", "NIU", 570),
    574 to CountryCode("Norfolk Island", "NF", "NFK", 574),
    580 to CountryCode("Northern Mariana Islands (the)", "MP", "MNP", 580),
    578 to CountryCode("Norway", "NO", "NOR", 578),
    512 to CountryCode("Oman", "OM", "OMN", 512),
    586 to CountryCode("Pakistan", "PK", "PAK", 586),
    585 to CountryCode("Palau", "PW", "PLW", 585),
    275 to CountryCode("Palestine, State of", "PS", "PSE", 275),
    591 to CountryCode("Panama", "PA", "PAN", 591),
    598 to CountryCode("Papua New Guinea", "PG", "PNG", 598),
    600 to CountryCode("Paraguay", "PY", "PRY", 600),
    604 to CountryCode("Peru", "PE", "PER", 604),
    608 to CountryCode("Philippines (the)", "PH", "PHL", 608),
    612 to CountryCode("Pitcairn", "PN", "PCN", 612),
    616 to CountryCode("Poland", "PL", "POL", 616),
    620 to CountryCode("Portugal", "PT", "PRT", 620),
    630 to CountryCode("Puerto Rico", "PR", "PRI", 630),
    634 to CountryCode("Qatar", "QA", "QAT", 634),
    807 to CountryCode("Republic of North Macedonia", "MK", "MKD", 807),
    642 to CountryCode("Romania", "RO", "ROU", 642),
    643 to CountryCode("Russian Federation (the)", "RU", "RUS", 643),
    646 to CountryCode("Rwanda", "RW", "RWA", 646),
    638 to CountryCode("Réunion", "RE", "REU", 638),
    652 to CountryCode("Saint Barthélemy", "BL", "BLM", 652),
    654 to CountryCode("Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", 654),
    659 to CountryCode("Saint Kitts and Nevis", "KN", "KNA", 659),
    662 to CountryCode("Saint Lucia", "LC", "LCA", 662),
    663 to CountryCode("Saint Martin (French part)", "MF", "MAF", 663),
    666 to CountryCode("Saint Pierre and Miquelon", "PM", "SPM", 666),
    670 to CountryCode("Saint Vincent and the Grenadines", "VC", "VCT", 670),
    882 to CountryCode("Samoa", "WS", "WSM", 882),
    674 to CountryCode("San Marino", "SM", "SMR", 674),
    678 to CountryCode("Sao Tome and Principe", "ST", "STP", 678),
    682 to CountryCode("Saudi Arabia", "SA", "SAU", 682),
    686 to CountryCode("Senegal", "SN", "SEN", 686),
    688 to CountryCode("Serbia", "RS", "SRB", 688),
    690 to CountryCode("Seychelles", "SC", "SYC", 690),
    694 to CountryCode("Sierra Leone", "SL", "SLE", 694),
    702 to CountryCode("Singapore", "SG", "SGP", 702),
    534 to CountryCode("Sint Maarten (Dutch part)", "SX", "SXM", 534),
    703 to CountryCode("Slovakia", "SK", "SVK", 703),
    705 to CountryCode("Slovenia", "SI", "SVN", 705),
    90 to CountryCode("Solomon Islands", "SB", "SLB", 90),
    706 to CountryCode("Somalia", "SO", "SOM", 706),
    710 to CountryCode("South Africa", "ZA", "ZAF", 710),
    239 to CountryCode("South Georgia and the South Sandwich Islands", "GS", "SGS", 239),
    728 to CountryCode("South Sudan", "SS", "SSD", 728),
    724 to CountryCode("Spain", "ES", "ESP", 724),
    144 to CountryCode("Sri Lanka", "LK", "LKA", 144),
    729 to CountryCode("Sudan (the)", "SD", "SDN", 729),
    740 to CountryCode("Suriname", "SR", "SUR", 740),
    744 to CountryCode("Svalbard and Jan Mayen", "SJ", "SJM", 744),
    752 to CountryCode("Sweden", "SE", "SWE", 752),
    756 to CountryCode("Switzerland", "CH", "CHE", 756),
    760 to CountryCode("Syrian Arab Republic", "SY", "SYR", 760),
    158 to CountryCode("Taiwan (Province of China)", "TW", "TWN", 158),
    762 to CountryCode("Tajikistan", "TJ", "TJK", 762),
    834 to CountryCode("Tanzania, United Republic of", "TZ", "TZA", 834),
    764 to CountryCode("Thailand", "TH", "THA", 764),
    626 to CountryCode("Timor-Leste", "TL", "TLS", 626),
    768 to CountryCode("Togo", "TG", "TGO", 768),
    772 to CountryCode("Tokelau", "TK", "TKL", 772),
    776 to CountryCode("Tonga", "TO", "TON", 776),
    780 to CountryCode("Trinidad and Tobago", "TT", "TTO", 780),
    788 to CountryCode("Tunisia", "TN", "TUN", 788),
    792 to CountryCode("Turkey", "TR", "TUR", 792),
    795 to CountryCode("Turkmenistan", "TM", "TKM", 795),
    796 to CountryCode("Turks and Caicos Islands (the)", "TC", "TCA", 796),
    798 to CountryCode("Tuvalu", "TV", "TUV", 798),
    800 to CountryCode("Uganda", "UG", "UGA", 800),
    804 to CountryCode("Ukraine", "UA", "UKR", 804),
    784 to CountryCode("United Arab Emirates (the)", "AE", "ARE", 784),
    826 to CountryCode(
        "United Kingdom of Great Britain and Northern Ireland (the)", "GB", "GBR", 826
    ),
    581 to CountryCode("United States Minor Outlying Islands (the)", "UM", "UMI", 581),
    840 to CountryCode("United States of America (the)", "US", "USA", 840),
    858 to CountryCode("Uruguay", "UY", "URY", 858),
    860 to CountryCode("Uzbekistan", "UZ", "UZB", 860),
    548 to CountryCode("Vanuatu", "VU", "VUT", 548),
    862 to CountryCode("Venezuela (Bolivarian Republic of)", "VE", "VEN", 862),
    704 to CountryCode("Viet Nam", "VN", "VNM", 704),
    92 to CountryCode("Virgin Islands (British)", "VG", "VGB", 92),
    850 to CountryCode("Virgin Islands (U.S.)", "VI", "VIR", 850),
    876 to CountryCode("Wallis and Futuna", "WF", "WLF", 876),
    732 to CountryCode("Western Sahara", "EH", "ESH", 732),
    887 to CountryCode("Yemen", "YE", "YEM", 887),
    894 to CountryCode("Zambia", "ZM", "ZMB", 894),
    716 to CountryCode("Zimbabwe", "ZW", "ZWE", 716),
    248 to CountryCode("Åland Islands", "AX", "ALA", 248),
)