/*
 * Copyright (c) 2025. Ingo Noka
 * This file belongs to project qrdata.
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
 * Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
 *
 */

package com.ingonoka.qrdata.transcode

/**
 * Currency code according to ISO standards
 *
 * A currency is used in a [country], it has a [name], a [shortName], a numerical [code] and
 * it is using a certain number of [decimals], such as `2` for `USD` meaning that there are `99`
 * cents in a Dollar.
 */
data class Currency(
    val country: String,
    val name: String,
    val shortName: String,
    val code: Int,
    val decimals: Int
)

/**
 * The currencies known to the application.
 */
@Suppress("SpellCheckingInspection")
val currencies: Map<Int, Currency> = mapOf(
    971 to Currency("AFGHANISTAN", "Afghani", "AFN", 971, 2),
    978 to Currency("ÅLAND ISLANDS", "Euro", "EUR", 978, 2),
    8 to Currency("ALBANIA", "Lek", "ALL", 8, 2),
    12 to Currency("ALGERIA", "Algerian Dinar", "DZD", 12, 2),
    840 to Currency("AMERICAN SAMOA", "US Dollar", "USD", 840, 2),
    978 to Currency("ANDORRA", "Euro", "EUR", 978, 2),
    973 to Currency("ANGOLA", "Kwanza", "AOA", 973, 2),
    951 to Currency("ANGUILLA", "East Caribbean Dollar", "XCD", 951, 2),
    951 to Currency("ANTIGUA AND BARBUDA", "East Caribbean Dollar", "XCD", 951, 2),
    396 to Currency("ARAB MONETARY FUND", "Arab Accounting Dinar", "XAD", 396, 2),
    32 to Currency("ARGENTINA", "Argentine Peso", "ARS", 32, 2),
    51 to Currency("ARMENIA", "Armenian Dram", "AMD", 51, 2),
    533 to Currency("ARUBA", "Aruban Florin", "AWG", 533, 2),
    36 to Currency("AUSTRALIA", "Australian Dollar", "AUD", 36, 2),
    978 to Currency("AUSTRIA", "Euro", "EUR", 978, 2),
    944 to Currency("AZERBAIJAN", "Azerbaijan Manat", "AZN", 944, 2),
    44 to Currency("BAHAMAS (THE)", "Bahamian Dollar", "BSD", 44, 2),
    48 to Currency("BAHRAIN", "Bahraini Dinar", "BHD", 48, 3),
    50 to Currency("BANGLADESH", "Taka", "BDT", 50, 2),
    52 to Currency("BARBADOS", "Barbados Dollar", "BBD", 52, 2),
    933 to Currency("BELARUS", "Belarusian Ruble", "BYN", 933, 2),
    978 to Currency("BELGIUM", "Euro", "EUR", 978, 2),
    84 to Currency("BELIZE", "Belize Dollar", "BZD", 84, 2),
    952 to Currency("BENIN", "CFA Franc BCEAO", "XOF", 952, 0),
    60 to Currency("BERMUDA", "Bermudian Dollar", "BMD", 60, 2),
    356 to Currency("BHUTAN", "Indian Rupee", "INR", 356, 2),
    64 to Currency("BHUTAN", "Ngultrum", "BTN", 64, 2),
    68 to Currency("BOLIVIA (PLURINATIONAL STATE OF)", "Boliviano", "BOB", 68, 2),
    984 to Currency("BOLIVIA (PLURINATIONAL STATE OF)", "Mvdol", "BOV", 984, 2),
    840 to Currency("BONAIRE, SINT EUSTATIUS AND SABA", "US Dollar", "USD", 840, 2),
    977 to Currency("BOSNIA AND HERZEGOVINA", "Convertible Mark", "BAM", 977, 2),
    72 to Currency("BOTSWANA", "Pula", "BWP", 72, 2),
    578 to Currency("BOUVET ISLAND", "Norwegian Krone", "NOK", 578, 2),
    986 to Currency("BRAZIL", "Brazilian Real", "BRL", 986, 2),
    840 to Currency("BRITISH INDIAN OCEAN TERRITORY (THE)", "US Dollar", "USD", 840, 2),
    96 to Currency("BRUNEI DARUSSALAM", "Brunei Dollar", "BND", 96, 2),
    975 to Currency("BULGARIA", "Bulgarian Lev", "BGN", 975, 2),
    952 to Currency("BURKINA FASO", "CFA Franc BCEAO", "XOF", 952, 0),
    108 to Currency("BURUNDI", "Burundi Franc", "BIF", 108, 0),
    132 to Currency("CABO VERDE", "Cabo Verde Escudo", "CVE", 132, 2),
    116 to Currency("CAMBODIA", "Riel", "KHR", 116, 2),
    950 to Currency("CAMEROON", "CFA Franc BEAC", "XAF", 950, 0),
    124 to Currency("CANADA", "Canadian Dollar", "CAD", 124, 2),
    136 to Currency("CAYMAN ISLANDS (THE)", "Cayman Islands Dollar", "KYD", 136, 2),
    950 to Currency("CENTRAL AFRICAN REPUBLIC (THE)", "CFA Franc BEAC", "XAF", 950, 0),
    950 to Currency("CHAD", "CFA Franc BEAC", "XAF", 950, 0),
    152 to Currency("CHILE", "Chilean Peso", "CLP", 152, 0),
    990 to Currency("CHILE", "Unidad de Fomento", "CLF", 990, 4),
    156 to Currency("CHINA", "Yuan Renminbi", "CNY", 156, 2),
    36 to Currency("CHRISTMAS ISLAND", "Australian Dollar", "AUD", 36, 2),
    36 to Currency("COCOS (KEELING) ISLANDS (THE)", "Australian Dollar", "AUD", 36, 2),
    170 to Currency("COLOMBIA", "Colombian Peso", "COP", 170, 2),
    970 to Currency("COLOMBIA", "Unidad de Valor Real", "COU", 970, 2),
    174 to Currency("COMOROS (THE)", "Comorian Franc ", "KMF", 174, 0),
    976 to Currency("CONGO (THE DEMOCRATIC REPUBLIC OF THE)", "Congolese Franc", "CDF", 976, 2),
    950 to Currency("CONGO (THE)", "CFA Franc BEAC", "XAF", 950, 0),
    554 to Currency("COOK ISLANDS (THE)", "New Zealand Dollar", "NZD", 554, 2),
    188 to Currency("COSTA RICA", "Costa Rican Colon", "CRC", 188, 2),
    952 to Currency("CÔTE D'IVOIRE", "CFA Franc BCEAO", "XOF", 952, 0),
    978 to Currency("CROATIA", "Euro", "EUR", 978, 2),
    192 to Currency("CUBA", "Cuban Peso", "CUP", 192, 2),
    532 to Currency("CURAÇAO", "Caribbean Guilder", "XCG", 532, 2),
    978 to Currency("CYPRUS", "Euro", "EUR", 978, 2),
    203 to Currency("CZECHIA", "Czech Koruna", "CZK", 203, 2),
    208 to Currency("DENMARK", "Danish Krone", "DKK", 208, 2),
    262 to Currency("DJIBOUTI", "Djibouti Franc", "DJF", 262, 0),
    951 to Currency("DOMINICA", "East Caribbean Dollar", "XCD", 951, 2),
    214 to Currency("DOMINICAN REPUBLIC (THE)", "Dominican Peso", "DOP", 214, 2),
    840 to Currency("ECUADOR", "US Dollar", "USD", 840, 2),
    818 to Currency("EGYPT", "Egyptian Pound", "EGP", 818, 2),
    222 to Currency("EL SALVADOR", "El Salvador Colon", "SVC", 222, 2),
    840 to Currency("EL SALVADOR", "US Dollar", "USD", 840, 2),
    950 to Currency("EQUATORIAL GUINEA", "CFA Franc BEAC", "XAF", 950, 0),
    232 to Currency("ERITREA", "Nakfa", "ERN", 232, 2),
    978 to Currency("ESTONIA", "Euro", "EUR", 978, 2),
    748 to Currency("ESWATINI", "Lilangeni", "SZL", 748, 2),
    230 to Currency("ETHIOPIA", "Ethiopian Birr", "ETB", 230, 2),
    978 to Currency("EUROPEAN UNION", "Euro", "EUR", 978, 2),
    238 to Currency("FALKLAND ISLANDS (THE) [MALVINAS]", "Falkland Islands Pound", "FKP", 238, 2),
    208 to Currency("FAROE ISLANDS (THE)", "Danish Krone", "DKK", 208, 2),
    242 to Currency("FIJI", "Fiji Dollar", "FJD", 242, 2),
    978 to Currency("FINLAND", "Euro", "EUR", 978, 2),
    978 to Currency("FRANCE", "Euro", "EUR", 978, 2),
    978 to Currency("FRENCH GUIANA", "Euro", "EUR", 978, 2),
    953 to Currency("FRENCH POLYNESIA", "CFP Franc", "XPF", 953, 0),
    978 to Currency("FRENCH SOUTHERN TERRITORIES (THE)", "Euro", "EUR", 978, 2),
    950 to Currency("GABON", "CFA Franc BEAC", "XAF", 950, 0),
    270 to Currency("GAMBIA (THE)", "Dalasi", "GMD", 270, 2),
    981 to Currency("GEORGIA", "Lari", "GEL", 981, 2),
    978 to Currency("GERMANY", "Euro", "EUR", 978, 2),
    936 to Currency("GHANA", "Ghana Cedi", "GHS", 936, 2),
    292 to Currency("GIBRALTAR", "Gibraltar Pound", "GIP", 292, 2),
    978 to Currency("GREECE", "Euro", "EUR", 978, 2),
    208 to Currency("GREENLAND", "Danish Krone", "DKK", 208, 2),
    951 to Currency("GRENADA", "East Caribbean Dollar", "XCD", 951, 2),
    978 to Currency("GUADELOUPE", "Euro", "EUR", 978, 2),
    840 to Currency("GUAM", "US Dollar", "USD", 840, 2),
    320 to Currency("GUATEMALA", "Quetzal", "GTQ", 320, 2),
    826 to Currency("GUERNSEY", "Pound Sterling", "GBP", 826, 2),
    324 to Currency("GUINEA", "Guinean Franc", "GNF", 324, 0),
    952 to Currency("GUINEA-BISSAU", "CFA Franc BCEAO", "XOF", 952, 0),
    328 to Currency("GUYANA", "Guyana Dollar", "GYD", 328, 2),
    332 to Currency("HAITI", "Gourde", "HTG", 332, 2),
    840 to Currency("HAITI", "US Dollar", "USD", 840, 2),
    36 to Currency("HEARD ISLAND AND McDONALD ISLANDS", "Australian Dollar", "AUD", 36, 2),
    978 to Currency("HOLY SEE (THE)", "Euro", "EUR", 978, 2),
    340 to Currency("HONDURAS", "Lempira", "HNL", 340, 2),
    344 to Currency("HONG KONG", "Hong Kong Dollar", "HKD", 344, 2),
    348 to Currency("HUNGARY", "Forint", "HUF", 348, 2),
    352 to Currency("ICELAND", "Iceland Krona", "ISK", 352, 0),
    356 to Currency("INDIA", "Indian Rupee", "INR", 356, 2),
    360 to Currency("INDONESIA", "Rupiah", "IDR", 360, 2),
    960 to Currency(
        "INTERNATIONAL MONETARY FUND(IMF)", "SDR(Special Drawing Right)", "XDR", 960, 0
    ),
    364 to Currency("IRAN (ISLAMIC REPUBLIC OF)", "Iranian Rial", "IRR", 364, 2),
    368 to Currency("IRAQ", "Iraqi Dinar", "IQD", 368, 3),
    978 to Currency("IRELAND", "Euro", "EUR", 978, 2),
    826 to Currency("ISLE OF MAN", "Pound Sterling", "GBP", 826, 2),
    376 to Currency("ISRAEL", "New Israeli Sheqel", "ILS", 376, 2),
    978 to Currency("ITALY", "Euro", "EUR", 978, 2),
    388 to Currency("JAMAICA", "Jamaican Dollar", "JMD", 388, 2),
    392 to Currency("JAPAN", "Yen", "JPY", 392, 0),
    826 to Currency("JERSEY", "Pound Sterling", "GBP", 826, 2),
    400 to Currency("JORDAN", "Jordanian Dinar", "JOD", 400, 3),
    398 to Currency("KAZAKHSTAN", "Tenge", "KZT", 398, 2),
    404 to Currency("KENYA", "Kenyan Shilling", "KES", 404, 2),
    36 to Currency("KIRIBATI", "Australian Dollar", "AUD", 36, 2),
    408 to Currency(
        "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)", "North Korean Won", "KPW", 408, 2
    ),
    410 to Currency("KOREA (THE REPUBLIC OF)", "Won", "KRW", 410, 0),
    414 to Currency("KUWAIT", "Kuwaiti Dinar", "KWD", 414, 3),
    417 to Currency("KYRGYZSTAN", "Som", "KGS", 417, 2),
    418 to Currency("LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)", "Lao Kip", "LAK", 418, 2),
    978 to Currency("LATVIA", "Euro", "EUR", 978, 2),
    422 to Currency("LEBANON", "Lebanese Pound", "LBP", 422, 2),
    426 to Currency("LESOTHO", "Loti", "LSL", 426, 2),
    710 to Currency("LESOTHO", "Rand", "ZAR", 710, 2),
    430 to Currency("LIBERIA", "Liberian Dollar", "LRD", 430, 2),
    434 to Currency("LIBYA", "Libyan Dinar", "LYD", 434, 3),
    756 to Currency("LIECHTENSTEIN", "Swiss Franc", "CHF", 756, 2),
    978 to Currency("LITHUANIA", "Euro", "EUR", 978, 2),
    978 to Currency("LUXEMBOURG", "Euro", "EUR", 978, 2),
    446 to Currency("MACAO", "Pataca", "MOP", 446, 2),
    969 to Currency("MADAGASCAR", "Malagasy Ariary", "MGA", 969, 2),
    454 to Currency("MALAWI", "Malawi Kwacha", "MWK", 454, 2),
    458 to Currency("MALAYSIA", "Malaysian Ringgit", "MYR", 458, 2),
    462 to Currency("MALDIVES", "Rufiyaa", "MVR", 462, 2),
    952 to Currency("MALI", "CFA Franc BCEAO", "XOF", 952, 0),
    978 to Currency("MALTA", "Euro", "EUR", 978, 2),
    840 to Currency("MARSHALL ISLANDS (THE)", "US Dollar", "USD", 840, 2),
    978 to Currency("MARTINIQUE", "Euro", "EUR", 978, 2),
    929 to Currency("MAURITANIA", "Ouguiya", "MRU", 929, 2),
    480 to Currency("MAURITIUS", "Mauritius Rupee", "MUR", 480, 2),
    978 to Currency("MAYOTTE", "Euro", "EUR", 978, 2),
    965 to Currency(
        "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP", "ADB Unit of Account", "XUA", 965,
        0
    ),
    484 to Currency("MEXICO", "Mexican Peso", "MXN", 484, 2),
    979 to Currency("MEXICO", "Mexican Unidad de Inversion (UDI)", "MXV", 979, 2),
    840 to Currency("MICRONESIA (FEDERATED STATES OF)", "US Dollar", "USD", 840, 2),
    498 to Currency("MOLDOVA (THE REPUBLIC OF)", "Moldovan Leu", "MDL", 498, 2),
    978 to Currency("MONACO", "Euro", "EUR", 978, 2),
    496 to Currency("MONGOLIA", "Tugrik", "MNT", 496, 2),
    978 to Currency("MONTENEGRO", "Euro", "EUR", 978, 2),
    951 to Currency("MONTSERRAT", "East Caribbean Dollar", "XCD", 951, 2),
    54 to Currency("MOROCCO", "Moroccan Dirham", "MAD", 504, 2),
    943 to Currency("MOZAMBIQUE", "Mozambique Metical", "MZN", 943, 2),
    104 to Currency("MYANMAR", "Kyat", "MMK", 104, 2),
    516 to Currency("NAMIBIA", "Namibia Dollar", "NAD", 516, 2),
    710 to Currency("NAMIBIA", "Rand", "ZAR", 710, 2),
    36 to Currency("NAURU", "Australian Dollar", "AUD", 36, 2),
    524 to Currency("NEPAL", "Nepalese Rupee", "NPR", 524, 2),
    978 to Currency("NETHERLANDS (THE)", "Euro", "EUR", 978, 2),
    953 to Currency("NEW CALEDONIA", "CFP Franc", "XPF", 953, 0),
    554 to Currency("NEW ZEALAND", "New Zealand Dollar", "NZD", 554, 2),
    558 to Currency("NICARAGUA", "Cordoba Oro", "NIO", 558, 2),
    952 to Currency("NIGER (THE)", "CFA Franc BCEAO", "XOF", 952, 0),
    566 to Currency("NIGERIA", "Naira", "NGN", 566, 2),
    554 to Currency("NIUE", "New Zealand Dollar", "NZD", 554, 2),
    36 to Currency("NORFOLK ISLAND", "Australian Dollar", "AUD", 36, 2),
    807 to Currency("NORTH MACEDONIA", "Denar", "MKD", 807, 2),
    840 to Currency("NORTHERN MARIANA ISLANDS (THE)", "US Dollar", "USD", 840, 2),
    578 to Currency("NORWAY", "Norwegian Krone", "NOK", 578, 2),
    512 to Currency("OMAN", "Rial Omani", "OMR", 512, 3),
    586 to Currency("PAKISTAN", "Pakistan Rupee", "PKR", 586, 2),
    840 to Currency("PALAU", "US Dollar", "USD", 840, 2),
    590 to Currency("PANAMA", "Balboa", "PAB", 590, 2),
    840 to Currency("PANAMA", "US Dollar", "USD", 840, 2),
    598 to Currency("PAPUA NEW GUINEA", "Kina", "PGK", 598, 2),
    600 to Currency("PARAGUAY", "Guarani", "PYG", 600, 0),
    604 to Currency("PERU", "Sol", "PEN", 604, 2),
    608 to Currency("PHILIPPINES (THE)", "Philippine Peso", "PHP", 608, 2),
    554 to Currency("PITCAIRN", "New Zealand Dollar", "NZD", 554, 2),
    985 to Currency("POLAND", "Zloty", "PLN", 985, 2),
    978 to Currency("PORTUGAL", "Euro", "EUR", 978, 2),
    840 to Currency("PUERTO RICO", "US Dollar", "USD", 840, 2),
    634 to Currency("QATAR", "Qatari Rial", "QAR", 634, 2),
    978 to Currency("RÉUNION", "Euro", "EUR", 978, 2),
    946 to Currency("ROMANIA", "Romanian Leu", "RON", 946, 2),
    643 to Currency("RUSSIAN FEDERATION (THE)", "Russian Ruble", "RUB", 643, 2),
    646 to Currency("RWANDA", "Rwanda Franc", "RWF", 646, 0),
    978 to Currency("SAINT BARTHÉLEMY", "Euro", "EUR", 978, 2),
    654 to Currency(
        "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", "Saint Helena Pound", "SHP", 654, 2
    ),
    951 to Currency("SAINT KITTS AND NEVIS", "East Caribbean Dollar", "XCD", 951, 2),
    951 to Currency("SAINT LUCIA", "East Caribbean Dollar", "XCD", 951, 2),
    978 to Currency("SAINT MARTIN (FRENCH PART)", "Euro", "EUR", 978, 2),
    978 to Currency("SAINT PIERRE AND MIQUELON", "Euro", "EUR", 978, 2),
    951 to Currency("SAINT VINCENT AND THE GRENADINES", "East Caribbean Dollar", "XCD", 951, 2),
    882 to Currency("SAMOA", "Tala", "WST", 882, 2),
    978 to Currency("SAN MARINO", "Euro", "EUR", 978, 2),
    930 to Currency("SAO TOME AND PRINCIPE", "Dobra", "STN", 930, 2),
    682 to Currency("SAUDI ARABIA", "Saudi Riyal", "SAR", 682, 2),
    952 to Currency("SENEGAL", "CFA Franc BCEAO", "XOF", 952, 0),
    941 to Currency("SERBIA", "Serbian Dinar", "RSD", 941, 2),
    690 to Currency("SEYCHELLES", "Seychelles Rupee", "SCR", 690, 2),
    925 to Currency("SIERRA LEONE", "Leone", "SLE", 925, 2),
    702 to Currency("SINGAPORE", "Singapore Dollar", "SGD", 702, 2),
    532 to Currency("SINT MAARTEN (DUTCH PART)", "Caribbean Guilder", "XCG", 532, 2),
    994 to Currency(
        "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS SUCRE", "Sucre", "XSU", 994, 0
    ),
    978 to Currency("SLOVAKIA", "Euro", "EUR", 978, 2),
    978 to Currency("SLOVENIA", "Euro", "EUR", 978, 2),
    90 to Currency("SOLOMON ISLANDS", "Solomon Islands Dollar", "SBD", 90, 2),
    706 to Currency("SOMALIA", "Somali Shilling", "SOS", 706, 2),
    710 to Currency("SOUTH AFRICA", "Rand", "ZAR", 710, 2),
    728 to Currency("SOUTH SUDAN", "South Sudanese Pound", "SSP", 728, 2),
    978 to Currency("SPAIN", "Euro", "EUR", 978, 2),
    144 to Currency("SRI LANKA", "Sri Lanka Rupee", "LKR", 144, 2),
    938 to Currency("SUDAN (THE)", "Sudanese Pound", "SDG", 938, 2),
    968 to Currency("SURINAME", "Surinam Dollar", "SRD", 968, 2),
    578 to Currency("SVALBARD AND JAN MAYEN", "Norwegian Krone", "NOK", 578, 2),
    752 to Currency("SWEDEN", "Swedish Krona", "SEK", 752, 2),
    756 to Currency("SWITZERLAND", "Swiss Franc", "CHF", 756, 2),
    947 to Currency("SWITZERLAND", "WIR Euro", "CHE", 947, 2),
    948 to Currency("SWITZERLAND", "WIR Franc", "CHW", 948, 2),
    760 to Currency("SYRIAN ARAB REPUBLIC", "Syrian Pound", "SYP", 760, 2),
    901 to Currency("TAIWAN (PROVINCE OF CHINA)", "New Taiwan Dollar", "TWD", 901, 2),
    972 to Currency("TAJIKISTAN", "Somoni", "TJS", 972, 2),
    834 to Currency("TANZANIA, UNITED REPUBLIC OF", "Tanzanian Shilling", "TZS", 834, 2),
    764 to Currency("THAILAND", "Baht", "THB", 764, 2),
    840 to Currency("TIMOR-LESTE", "US Dollar", "USD", 840, 2),
    952 to Currency("TOGO", "CFA Franc BCEAO", "XOF", 952, 0),
    554 to Currency("TOKELAU", "New Zealand Dollar", "NZD", 554, 2),
    776 to Currency("TONGA", "Pa’anga", "TOP", 776, 2),
    780 to Currency("TRINIDAD AND TOBAGO", "Trinidad and Tobago Dollar", "TTD", 780, 2),
    788 to Currency("TUNISIA", "Tunisian Dinar", "TND", 788, 3),
    949 to Currency("TÜRKİYE", "Turkish Lira", "TRY", 949, 2),
    934 to Currency("TURKMENISTAN", "Turkmenistan New Manat", "TMT", 934, 2),
    840 to Currency("TURKS AND CAICOS ISLANDS (THE)", "US Dollar", "USD", 840, 2),
    36 to Currency("TUVALU", "Australian Dollar", "AUD", 36, 2),
    800 to Currency("UGANDA", "Uganda Shilling", "UGX", 800, 0),
    980 to Currency("UKRAINE", "Hryvnia", "UAH", 980, 2),
    784 to Currency("UNITED ARAB EMIRATES (THE)", "UAE Dirham", "AED", 784, 2),
    826 to Currency(
        "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)", "Pound Sterling", "GBP", 826,
        2
    ),
    840 to Currency("UNITED STATES MINOR OUTLYING ISLANDS (THE)", "US Dollar", "USD", 840, 2),
    840 to Currency("UNITED STATES OF AMERICA (THE)", "US Dollar", "USD", 840, 2),
    997 to Currency("UNITED STATES OF AMERICA (THE)", "US Dollar (Next day)", "USN", 997, 2),
    858 to Currency("URUGUAY", "Peso Uruguayo", "UYU", 858, 2),
    940 to Currency("URUGUAY", "Uruguay Peso en Unidades Indexadas (UI)", "UYI", 940, 0),
    927 to Currency("URUGUAY", "Unidad Previsional", "UYW", 927, 4),
    860 to Currency("UZBEKISTAN", "Uzbekistan Sum", "UZS", 860, 2),
    548 to Currency("VANUATU", "Vatu", "VUV", 548, 0),
    928 to Currency("VENEZUELA (BOLIVARIAN REPUBLIC OF)", "Bolívar Soberano", "VES", 928, 2),
    926 to Currency("VENEZUELA (BOLIVARIAN REPUBLIC OF)", "Bolívar Soberano", "VED", 926, 2),
    704 to Currency("VIET NAM", "Dong", "VND", 704, 0),
    840 to Currency("VIRGIN ISLANDS (BRITISH)", "US Dollar", "USD", 840, 2),
    840 to Currency("VIRGIN ISLANDS (U.S.)", "US Dollar", "USD", 840, 2),
    953 to Currency("WALLIS AND FUTUNA", "CFP Franc", "XPF", 953, 0),
    504 to Currency("WESTERN SAHARA", "Moroccan Dirham", "MAD", 504, 2),
    886 to Currency("YEMEN", "Yemeni Rial", "YER", 886, 2),
    967 to Currency("ZAMBIA", "Zambian Kwacha", "ZMW", 967, 2),
    924 to Currency("ZIMBABWE", "Zimbabwe Gold", "ZWG", 924, 2),
    955 to Currency(
        "ZZ01_Bond Markets Unit European_EURCO",
        "Bond Markets Unit European Composite Unit (EURCO)",
        "XBA",
        955,
        0
    ),
    956 to Currency(
        "ZZ02_Bond Markets Unit European_EMU-6",
        "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
        "XBB",
        956,
        0
    ),
    957 to Currency(
        "ZZ03_Bond Markets Unit European_EUA-9",
        "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
        "XBC",
        957,
        0
    ),
    958 to Currency(
        "ZZ04_Bond Markets Unit European_EUA-17",
        "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
        "XBD",
        958,
        0
    ),
    963 to Currency(
        "ZZ06_Testing_Code", "Codes specifically reserved for testing purposes", "XTS", 963, 0
    ),
    999 to Currency(
        "ZZ07_No_Currency",
        "The codes assigned for transactions where no currency is involved",
        "XXX",
        999,
        0
    ),
    959 to Currency("ZZ08_Gold", "Gold", "XAU", 959, 0),
    964 to Currency("ZZ09_Palladium", "Palladium", "XPD", 964, 0),
    962 to Currency("ZZ10_Platinum", "Platinum", "XPT", 962, 0),
    961 to Currency("ZZ11_Silver", "Silver", "XAG", 961, 0)
)