/*
 * Copyright (c) 2025. Ingo Noka
 * This file belongs to project qrdata.
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
 * Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
 *
 */

package com.ingonoka.qrdata.transcode

/**
 * Merchant category codes known to the application.
 */
val merchantCategories: Map<Int, String> = mapOf(
    7623 to "A/C, Refrigeration Repair",
    8931 to "Accounting/Bookkeeping Services",
    7311 to "Advertising Services",
    763 to "Agricultural Cooperative",
    4511 to "Airlines, Air Carriers",
    4582 to "Airports, Flying Fields",
    4119 to "Ambulance Services",
    7996 to "Amusement Parks/Carnivals",
    5937 to "Antique Reproductions",
    5932 to "Antique Shops",
    7998 to "Aquariums",
    8911 to "Architectural/Surveying Services",
    5971 to "Art Dealers and Galleries",
    5970 to "Artists Supply and Craft Shops",
    7531 to "Auto Body Repair Shops",
    7535 to "Auto Paint Shops",
    7538 to "Auto Service Shops",
    5531 to "Auto and Home Supply Stores",
    6011 to "Automated Cash Disburse",
    5542 to "Automated Fuel Dispensers",
    8675 to "Automobile Associations",
    5533 to "Automotive Parts and Accessories Stores",
    5532 to "Automotive Tire Stores",
    9223 to "Bail and Bond Payments (payment to the surety for the bond, not the actual bond paid to the government agency)",
    5462 to "Bakeries",
    7929 to "Bands, Orchestras",
    7230 to "Barber and Beauty Shops",
    7995 to "Betting/Casino Gambling",
    5940 to "Bicycle Shops",
    7932 to "Billiard/Pool Establishments",
    5551 to "Boat Dealers",
    4457 to "Boat Rentals and Leases",
    5942 to "Book Stores",
    5192 to "Books, Periodicals, and Newspapers",
    7933 to "Bowling Alleys",
    4131 to "Bus Lines",
    8244 to "Business/Secretarial Schools",
    7278 to "Buying/Shopping Services",
    4899 to "Cable, Satellite, and Other Pay Television and Radio",
    5946 to "Camera and Photographic Supply Stores",
    5441 to "Candy, Nut, and Confectionery Stores",
    7512 to "Car Rental Agencies",
    7542 to "Car Washes",
    5511 to "Car and Truck Dealers (New & Used) Sales, Service, Repairs Parts and Leasing",
    5521 to "Car and Truck Dealers (Used Only) Sales, Service, Repairs Parts and Leasing",
    1750 to "Carpentry Services",
    7217 to "Carpet/Upholstery Cleaning",
    5811 to "Caterers",
    8398 to "Charitable and Social Service Organizations - Fundraising",
    5169 to "Chemicals and Allied Products (Not Elsewhere Classified)",
    8351 to "Child Care Services",
    5641 to "Children's and Infants Wear Stores",
    8049 to "Chiropodists, Podiatrists",
    8041 to "Chiropractors",
    5993 to "Cigar Stores and Stands",
    8641 to "Civic, Social, Fraternal Associations",
    7349 to "Cleaning and Maintenance",
    7296 to "Clothing Rental",
    8220 to "Colleges, Universities",
    5046 to "Commercial Equipment (Not Elsewhere Classified)",
    5139 to "Commercial Footwear",
    7333 to "Commercial Photography, Art and Graphics",
    4111 to "Commuter Transport, Ferries",
    4816 to "Computer Network Services",
    7372 to "Computer Programming",
    7379 to "Computer Repair",
    5734 to "Computer Software Stores",
    5045 to "Computers, Peripherals, and Software",
    1771 to "Concrete Work Services",
    5039 to "Construction Materials (Not Elsewhere Classified)",
    7392 to "Consulting, Public Relations",
    8241 to "Correspondence Schools",
    5977 to "Cosmetic Stores",
    7277 to "Counseling Services",
    7997 to "Country Clubs",
    4215 to "Courier Services",
    9211 to "Court Costs, Including Alimony and Child Support - Courts of Law",
    7321 to "Credit Reporting Agencies",
    4411 to "Cruise Lines",
    5451 to "Dairy Products Stores",
    7911 to "Dance Hall, Studios, Schools",
    7273 to "Dating/Escort Services",
    8021 to "Dentists, Orthodontists",
    5311 to "Department Stores",
    7393 to "Detective Agencies",
    5815 to "Digital Goods Media – Books, Movies, Music",
    5817 to "Digital Goods – Applications (Excludes Games)",
    5816 to "Digital Goods – Games",
    5818 to "Digital Goods – Large Digital Goods Merchant",
    5964 to "Direct Marketing - Catalog Merchant",
    5965 to "Direct Marketing - Combination Catalog and Retail Merchant",
    5967 to "Direct Marketing - Inbound Telemarketing",
    5960 to "Direct Marketing - Insurance Services",
    5969 to "Direct Marketing - Other",
    5966 to "Direct Marketing - Outbound Telemarketing",
    5968 to "Direct Marketing - Subscription",
    5962 to "Direct Marketing - Travel",
    5310 to "Discount Stores",
    8011 to "Doctors",
    5963 to "Door-To-Door Sales",
    5714 to "Drapery, Window Covering, and Upholstery Stores",
    5813 to "Drinking Places",
    5912 to "Drug Stores and Pharmacies",
    5122 to "Drugs, Drug Proprietaries, and Druggist Sundries",
    7216 to "Dry Cleaners",
    5099 to "Durable Goods (Not Elsewhere Classified)",
    5309 to "Duty Free Stores",
    5812 to "Eating Places, Restaurants",
    8299 to "Educational Services",
    5997 to "Electric Razor Stores",
    5552 to "Electric Vehicle Charging",
    5065 to "Electrical Parts and Equipment",
    1731 to "Electrical Services",
    7622 to "Electronics Repair Shops",
    5732 to "Electronics Stores",
    8211 to "Elementary, Secondary Schools",
    9702 to "Emergency Services (GCAS) (Visa use only)",
    7361 to "Employment/Temp Agencies",
    7394 to "Equipment Rental",
    7342 to "Exterminating Services",
    5651 to "Family Clothing Stores",
    5814 to "Fast Food Restaurants",
    6012 to "Financial Institutions",
    9222 to "Fines - Government Administrative Entities",
    5718 to "Fireplace, Fireplace Screens, and Accessories Stores",
    5713 to "Floor Covering Stores",
    5992 to "Florists",
    5193 to "Florists Supplies, Nursery Stock, and Flowers",
    5422 to "Freezer and Locker Meat Provisioners",
    5983 to "Fuel Dealers (Non Automotive)",
    7261 to "Funeral Services, Crematories",
    7641 to "Furniture Repair, Refinishing",
    5712 to "Furniture, Home Furnishings, and Equipment Stores, Except Appliances",
    5681 to "Furriers and Fur Shops",
    1520 to "General Services",
    5947 to "Gift, Card, Novelty, and Souvenir Shops",
    5231 to "Glass, Paint, and Wallpaper Stores",
    5950 to "Glassware, Crystal Stores",
    7992 to "Golf Courses - Public",
    7801 to "Government Licensed On-line Casinos (On-Line Gambling)(US Region only)",
    9399 to "Government Services (Not Elsewhere Classified)",
    7802 to "Government-Licensed Horse/Dog Racing (US Region only)",
    9406 to "Government-Owned Lotteries (Non-US region)",
    7800 to "Government-Owned Lotteries (US Region only)",
    5411 to "Grocery Stores, Supermarkets",
    5251 to "Hardware Stores",
    5072 to "Hardware, Equipment, and Supplies",
    7298 to "Health and Beauty Spas",
    5975 to "Hearing Aids Sales and Supplies",
    1711 to "Heating, Plumbing, A/C",
    5945 to "Hobby, Toy, and Game Shops",
    5200 to "Home Supply Warehouse Stores",
    8062 to "Hospitals",
    7011 to "Hotels, Motels, and Resorts",
    5722 to "Household Appliance Stores",
    5085 to "Industrial Supplies (Not Elsewhere Classified)",
    7375 to "Information Retrieval Services",
    6399 to "Insurance - Default",
    6300 to "Insurance Underwriting, Premiums",
    9950 to "Intra-Company Purchases",
    5944 to "Jewelry Stores, Watches, Clocks, and Silverware Stores",
    780 to "Landscaping Services",
    7211 to "Laundries",
    7210 to "Laundry, Cleaning Services",
    8111 to "Legal Services, Attorneys",
    5948 to "Luggage and Leather Goods Stores",
    5211 to "Lumber, Building Materials Stores",
    6010 to "Manual Cash Disburse",
    4468 to "Marinas, Service and Supplies",
    1740 to "Masonry, Stonework, and Plaster",
    7297 to "Massage Parlors",
    8099 to "Medical Services",
    8071 to "Medical and Dental Labs",
    5047 to "Medical, Dental, Ophthalmic, and Hospital Equipment and Supplies",
    8699 to "Membership Organizations",
    5611 to "Mens and Boys Clothing and Accessories Stores",
    5691 to "Mens, Women's Clothing Stores",
    5051 to "Metal Service Centers",
    5699 to "Miscellaneous Apparel and Accessory Shops",
    5599 to "Miscellaneous Auto Dealers",
    7399 to "Miscellaneous Business Services",
    5499 to "Miscellaneous Food Stores - Convenience Stores and Specialty Markets",
    5399 to "Miscellaneous General Merchandise",
    7299 to "Miscellaneous General Services",
    5719 to "Miscellaneous Home Furnishing Specialty Stores",
    2741 to "Miscellaneous Publishing and Printing",
    7999 to "Miscellaneous Recreation Services",
    7699 to "Miscellaneous Repair Shops",
    5999 to "Miscellaneous Specialty Retail",
    5271 to "Mobile Home Dealers",
    7832 to "Motion Picture Theaters",
    4214 to "Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery Services",
    5592 to "Motor Homes Dealers",
    5013 to "Motor Vehicle Supplies and New Parts",
    5571 to "Motorcycle Shops and Dealers",
    5561 to "Motorcycle Shops, Dealers",
    5733 to "Music Stores-Musical Instruments, Pianos, and Sheet Music",
    5994 to "News Dealers and Newsstands",
    6051 to "Non-FI, Money Orders",
    6540 to "Non-FI, Stored Value Card Purchase/Load",
    5199 to "Nondurable Goods (Not Elsewhere Classified)",
    5261 to "Nurseries, Lawn and Garden Supply Stores",
    8050 to "Nursing/Personal Care",
    5021 to "Office and Commercial Furniture",
    8043 to "Opticians, Eyeglasses",
    8042 to "Optometrists, Ophthalmologist",
    5976 to "Orthopedic Goods - Prosthetic Devices",
    8031 to "Osteopaths",
    5921 to "Package Stores-Beer, Wine, and Liquor",
    5198 to "Paints, Varnishes, and Supplies",
    7523 to "Parking Lots, Garages",
    4112 to "Passenger Railways",
    5933 to "Pawn Shops",
    5995 to "Pet Shops, Pet Food, and Supplies",
    5172 to "Petroleum and Petroleum Products",
    7395 to "Photo Developing",
    7221 to "Photographic Studios",
    5044 to "Photographic, Photocopy, Microfilm Equipment, and Supplies",
    7829 to "Picture/Video Production",
    5131 to "Piece Goods, Notions, and Other Dry Goods",
    5074 to "Plumbing, Heating Equipment, and Supplies",
    8651 to "Political Organizations",
    9402 to "Postal Services - Government Only",
    5094 to "Precious Stones and Metals, Watches and Jewelry",
    8999 to "Professional Services",
    4225 to "Public Warehousing and Storage - Farm Products, Refrigerated Goods, Household Goods, and Storage",
    7338 to "Quick Copy, Repro, and Blueprint",
    4011 to "Railroads",
    6513 to "Real Estate Agents and Managers - Rentals",
    5735 to "Record Stores",
    7519 to "Recreational Vehicle Rentals",
    5973 to "Religious Goods Stores",
    8661 to "Religious Organizations",
    1761 to "Roofing/Siding, Sheet Metal",
    7339 to "Secretarial Support Services",
    6211 to "Security Brokers/Dealers",
    5541 to "Service Stations",
    5949 to "Sewing, Needlework, Fabric, and Piece Goods Stores",
    7251 to "Shoe Repair/Hat Cleaning",
    5661 to "Shoe Stores",
    7629 to "Small Appliance Repair",
    5598 to "Snowmobile Dealers",
    1799 to "Special Trade Services",
    2842 to "Specialty Cleaning",
    5941 to "Sporting Goods Stores",
    7032 to "Sporting/Recreation Camps",
    7941 to "Sports Clubs/Fields",
    5655 to "Sports and Riding Apparel Stores",
    5972 to "Stamp and Coin Stores",
    5943 to "Stationery Stores, Office, and School Supply Stores",
    5111 to "Stationery, Office Supplies, Printing and Writing Paper",
    5996 to "Swimming Pools Sales",
    4723 to "TUI Travel - Germany",
    5697 to "Tailors, Alterations",
    9311 to "Tax Payments - Government Agencies",
    7276 to "Tax Preparation Services",
    4121 to "Taxicabs/Limousines",
    4812 to "Telecommunication Equipment and Telephone Sales",
    4814 to "Telecommunication Services",
    4821 to "Telegraph Services",
    5998 to "Tent and Awning Shops",
    8734 to "Testing Laboratories",
    7922 to "Theatrical Ticket Agencies",
    7012 to "Timeshares",
    7534 to "Tire Retreading and Repair",
    4784 to "Tolls/Bridge Fees",
    7991 to "Tourist Attractions and Exhibits",
    7549 to "Towing Services",
    7033 to "Trailer Parks, Campgrounds",
    4789 to "Transportation Services (Not Elsewhere Classified)",
    4722 to "Travel Agencies, Tour Operators",
    7513 to "Truck/Utility Trailer Rentals",
    2791 to "Typesetting, Plate Making, and Related Services",
    5978 to "Typewriter Stores",
    9405 to "U.S. Federal Government Agencies or Departments",
    5137 to "Uniforms, Commercial Clothing",
    5931 to "Used Merchandise and Secondhand Stores",
    4900 to "Utilities",
    5331 to "Variety Stores",
    742 to "Veterinary Services",
    7993 to "Video Amusement Game Supplies",
    7994 to "Video Game Arcades",
    7841 to "Video Tape Rental Stores",
    8249 to "Vocational/Trade Schools",
    7631 to "Watch/Jewelry Repair",
    7692 to "Welding Repair",
    5300 to "Wholesale Clubs",
    5698 to "Wig and Toupee Stores",
    4829 to "Wires, Money Orders",
    5631 to "Women's Accessory and Specialty Shops",
    5621 to "Women's Ready-To-Wear Stores",
    5935 to "Wrecking and Salvage Yards",
)
